FROM node:22-alpine AS builder
RUN corepack enable
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.29-alpine AS runner
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo '$TZ' > /etc/timezone
RUN rm -rf /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["sh","-c","sed -i \"s/api_portal/$API_PORTAL/g\" /etc/nginx/nginx.conf ;sed -i \"s/protocol/$PROTOCOL/g\" /etc/nginx/nginx.conf ; nginx -g 'daemon off;'"]
EXPOSE 80