FROM node:22-alpine as builder

WORKDIR /app
COPY package.json yarn.lock tsconfig.json ./
RUN yarn install --production --frozen-lockfile
COPY . .
RUN npx tsc

FROM node:22-alpine as runner

RUN apk add --no-cache curl
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/tsconfig.json ./tsconfig.json
CMD ["yarn", "start"]
EXPOSE 3000