FROM node:22-alpine AS builder

WORKDIR /app
COPY ./package.json ./yarn.lock ./tsconfig.json ./
RUN yarn install --frozen-lockfile
COPY . .
RUN export NODE_OPTIONS="--max-old-space-size=8192"
RUN yarn build

FROM node:22-alpine AS runner

RUN apk add --no-cache curl
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/dist /app/dist
RUN export NODE_OPTIONS="--max-old-space-size=8192"
CMD ["yarn", "start"]
EXPOSE 3000